### ISSUE TITLE
.github/header-checker-lint.yml ignoreFiles not working

### ISSUE THREAD

**Issue by aabmass** [googleapis/repo-automation-bots#1038]
I am using the header-checker-lint and want to ignore some config files (`.prettierrc.js`). The header checker lint doesn't seem to respect my config in `.github/header-checker-lint.yml` `ignoreFiles` array. I originally tried `.bots/header-checker-lint.json` as well but I see the docs are out of date (https://github.com/googleapis/repo-automation-bots/issues/897#issuecomment-679426370). Is there something I'm missing here?

#### Steps to reproduce

Here is a repro PR in a brand new repo: https://github.com/aabmass/gts-header-checker-lint-repro/pull/1. The header-check fails even though the failing file should be ignored.

**Comment by chingor13** [comment]
Thanks for filing this!

I think what's happening is probot's `context.config()` method is reading config from the default branch (not from the PR branch). So in the example PR, the config is not in your `main` branch. This is a design decision by probot (likely to ensure the configuration is trusted by default).

It's possible in this case, that we try to read the config from the current branch.

**Comment by tmatsuo** [comment]
So the workaround in this case now is to first merge `.github/header-checker-lint.yml` first then sync your PR to include that file.
I just released https://github.com/googleapis/repo-automation-bots/tree/master/packages/bot-config-utils
(which is broken right now).

Maybe I can add a capability of returning the new config from the config checker so that the bot can opt in using that config instead of the config in the main branch.

**Comment by tmatsuo** [comment]
I'll add one more PR to fix this.
