### ISSUE TITLE
Please install auto-label bot on google-cloud-python

### ISSUE THREAD

**Issue by busunkim96** [googleapis/repo-automation-bots#1277]
I'd like to install auto-label bot on https://github.com/googleapis/google-cloud-python. 

I tried to use the [installation link](https://github.com/apps/product-auto-label) but it looks like I have insufficient permissions. :)

Thanks!

**Comment by sofisl** [comment]
Hi @busunkim96,

The good news is that the bot should actually be installed! Since this repo isn't tied to a specific product, auto-label will try to auto-detect the right label from the issue title. I tried experimenting a bit last night and I saw it in the logs.

The bad news is that, for some reason, auto-detect doesn't seem to be detecting the product from the title. @tbpg, I tried testing auto-detect with some of the example titles, but it didn't seem to be adding a label (see example [issue](https://github.com/googleapis/google-cloud-python/issues/10526
)). Would you happen to know what the issue is? If you don't have the time, feel free to let me know and I can investigate further!

**Comment by tbpg** [comment]
It appears to be working: https://github.com/googleapis/google-cloud-python/issues/10529.

Here are the supported issue formats:
https://github.com/googleapis/repo-automation-bots/blob/master/packages/auto-label/README.md#product-label

If there is another format you would like to support, you can add it here or let me know & I can give it a shot:
https://github.com/googleapis/repo-automation-bots/blob/f3cdd7cd23980a4e120b0009dfa6f746b8dabeb3/packages/auto-label/src/helper.ts#L76

**Comment by busunkim96** [comment]
Ah that's awesome! Thank you both for the help 🙏
