### ISSUE TITLE
bazel query does not find dotnet build targets

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#1338]
Bazel bot uses [this bazel query and regular expression](https://github.com/googleapis/repo-automation-bots/blob/a4ae53d45996ded87315e40ee496a0c7adcee9d8/packages/bazel-bot/docker-image/generate-googleapis-gen.sh#L72) to find the build targets:

```
bazel query $BAZEL_FLAGS \
'filter("-(go|csharp|java|php|ruby|nodejs|py)\.tar\.gz$", kind("generated file", //...:*))' \
| grep -v -E ":(proto|grpc|gapic)-.*-java\.tar\.gz$")
```

I see two issues:

1.  It fails to find csharp generated files like `google-cloud-domains-v1beta1-csharp.tar.gz`.
2. It smells bad.  

I seek a better bazel query.

**Comment by vam-google** [comment]
Try the following query:
```sh
bazel query $BAZEL_FLAGS \
  'filter("-(go|csharp|java|php|ruby|nodejs|py)$", kind("rule", //...:*))' \
  | grep -v -E ":(proto|grpc|gapic)-.*-java$"
```

It is very similar to the original one, but filters by target names instead of the generated files. The C# rules use different style for declaring generated output, which still results into generating the `.tar.gz` files but those do not match the `generated files` bazel query langauge filter per se.
