### ISSUE TITLE
flakybot binary dies when one of the files was deleted

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1475]
An example build log:
https://source.cloud.google.com/results/invocations/4ea58817-a9c1-4b41-b553-3ed0dddd0bd1/log

```
[FlakyBot] Sending logs to Flaky Bot...
[FlakyBot] See https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot.
[FlakyBot] Error publishing logs: lstat app_engine_app/noxfile.py: no such file or directory
```

This is happening in `iap` directory. This directory has `app_engine_app` sub directory. This sub directory has its own test. The test driver is running these tests in parallel. The test driver copy noxfile.py into the target directory before running the test, and delete it after the test.

Can flakybot binary ignore this failure?

**Comment by tbpg** [comment]
Very interesting... Thanks for the report.

Here is where the error comes from:
https://github.com/googleapis/repo-automation-bots/blob/947ec4582e8f22cd0fc0a87e36d428e483e05e95/packages/flakybot/flakybot.go#L184-L188

From https://golang.org/pkg/path/filepath/#Walk:
> Walk is less efficient than WalkDir, introduced in Go 1.16, which avoids calling os.Lstat on every visited file or directory.

So, perhaps this will be fixed by upgrading to Go 1.16 and using `WalkDir`.
