### ISSUE TITLE
test(owlbot): run shellcheck for bash scripts

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#1994]
We run shellcheck for scripts in `scripts` directory, but we don't run shellcheck for scripts in owlbot.

**Comment by SurferJeffAtGoogle** [comment]
I ran the script through https://www.shellcheck.net/

I see about 10 legacy warnings like `Use $() instead of backticks.`

I see about 5 warnings that $vars should be enclosed in quotes.  Most are irrelevant because the contents are hash strings.  Some are wrong to the point of breaking the code.  For example, following the recommendation would break the code:
```
[Line 82:](javascript:setPosition(82, 24))
        && bazel query $BAZEL_FLAGS  'filter("-(go|csharp|java|php|ruby|nodejs|py)$", kind("rule", //...:*))' \
                       ^-- [SC2086](https://www.shellcheck.net/wiki/SC2086) (info): Double quote to prevent globbing and word splitting.
```

I specifically want word splitting.  Without word splitting, the command would fail.

So, I suggest that we manually run the script through this tool every once in a while.   The signal to noise ratio is too low to run automatically.
