### ISSUE TITLE
owlbot failed to open PRs after a post-processor image update

### ISSUE THREAD

**Issue by parthea** [googleapis/repo-automation-bots#2147]
[This PR](https://github.com/googleapis/synthtool/commit/2514a9985b36626acb384dff903c62ac5963441b) triggered a new python post processor image to be created. When a new post processor image is created, owl bot should open PRs in python repos in the `googleapis` org which includes the post-processor updates but that didn't happen. 

@SurferJeffAtGoogle confirmed that the pubsub message was delivered (see screenshot below) but didn't [see messages from owl bot in the logs](https://github.com/googleapis/repo-automation-bots/blob/f8cf9a4063c41762b9ba0ed1463e0a2068cf1e4f/packages/owl-bot/src/owl-bot.ts#L139). See his notes below:

> When I search the logs for this [image's digest](https://pantheon.corp.google.com/logs/query;query=b6c55c48761d2ee099a68c94452125cbe02ac746d0497a424dc77751f0d11278;timeRange=2021-06-22T14:35:38.481Z%2F2021-06-22T16:35:38.481393Z;cursorTimestamp=2021-06-22T15:51:08.175849565Z?project=repo-automation-bots) I only find log messages from cloud build. I expect to also see messages from Owl Bot

This screenshot shows that a pub sub message was received:
![image](https://user-images.githubusercontent.com/5184014/122968148-38987e00-d359-11eb-8dd9-50421eb6a521.png)

**Comment by SurferJeffAtGoogle** [comment]
When I search the logs for this image's digest https://pantheon.corp.google.com/logs/query;query=b6c55c48761d2ee099a68c94452125cbe02ac746d0497a424dc77751f0d11278;timeRange=2021-06-22T14:35:38.481Z%2F2021-06-22T16:35:38.481393Z;cursorTimestamp=2021-06-22T15:51:08.175849565Z?project=repo-automation-bots

I only find log messages from cloud build.

![image](https://user-images.githubusercontent.com/11778530/122969226-404c2880-d341-11eb-9bd1-597e6920f8d1.png)

I expect to see a log message from owl bot because of this code:
https://github.com/googleapis/repo-automation-bots/blob/85cf6dcf35b6f0342ab01e639e821a258670cbd9/packages/owl-bot/src/owl-bot.ts#L134
But no such line is logged.

@bcoe We also occasionally see the owl bot post processor not run.  This smells similar.  Thoughts?

**Comment by SurferJeffAtGoogle** [comment]
@chingor13 I think this issue is relevant to how we configure retries.
