### ISSUE TITLE
gcf-utils: the server returns 200 when the signature verification fails

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2224]
I'm trying to deploy a new bot on Cloud Run and observed that the server returns the status code 200 even when the signature verification failed.

**Comment by tmatsuo** [comment]
Oh it actually returns 400 correctly, but the log shows status 200.

**Comment by chingor13** [comment]
It turns out that `response.send({status: 400, body: 'some json'}) actually returns a 200 with a JSON body containing the status and body fields.

We can fix this, but maybe we want to return 200 because we don't actually want Cloud Tasks to retry. Or perhaps return a 200 if the request is from tasks and 400 otherwise.

**Comment by chingor13** [comment]
We're going to just return 400 in all cases.
