### ISSUE TITLE
bug(release-please): dies with MissingRequiredFileError

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#2276]
```
    MissingRequiredFileError: JavaYoshi (java-pubsublite-flink): Missing required file: versions.txt
        at JavaYoshi.getVersionManifestContent (/workspace/node_modules/release-please/build/src/releasers/java-yoshi.js:56:31)
        at runMicrotasks (<anonymous>)
```

**Comment by tmatsuo** [comment]
blunderbuss didn't do anything other than removing the label...

**Comment by chingor13** [comment]
As of release-please 11.16.0, we throw better error messages so that the caller can handle them better. In this case, the repository is not configured correctly for a YoshiJava release (missing versions.txt). This is a fatal error as far as release-please is concerned.

The proposal in go/github-bot-error-handling would treat this as a repository error and open an issue on the java-pubsublite-flink repo.

For now, we can probably log (warn) on this error and not crash.
