### ISSUE TITLE
Bazelbot is is failing to update googleapis-gen for most recent changes in googleapis

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2354]
Last update to `googleapis-gen` was 24 hours ago:

https://github.com/googleapis/googleapis-gen/commits/master

There have been additional updates to `googlepais` in this time period:

https://github.com/googleapis/googleapis/commits/master

The job seems to be succeeding, but runs faster than I'd expect:

https://pantheon.corp.google.com/cloud-build/builds?query=trigger_id%3D%22cbeca61c-a35c-4c82-a998-f96b63ea8925%22&project=repo-automation-bots

---

My hunch is that this is related to branch renaming, but it's not obvious to me where the issue is.

**Comment by SurferJeffAtGoogle** [comment]
Bazelbot appears to be working normally.

Bazelbot won't create a new commit in googleapis-gen if there are no changes in the generated code.  In that scenario it will create a new tag on the head commit.

For example, consider the most recent 3 commits to googleapis:

```
09a618302 fix: Update DocumentUnderstandingService default_host in v1beta2 from a regional endpoint, to non-regional
08ae6839a chore: regenerate API index
6ef6c29b0 feat(googleads): protos for v8.1 of Google Ads API
```

We see only two commits in googleapis-gen:
```
6a6d8a449e (HEAD -> master, tag: googleapis-09a61830286f02b7cc3c203cf99cd8d7039504b1, origin/master) fix: Update DocumentUnderstandingService default_host in v1beta2 from a regional endpoint, to non-regional
ab07da4c35 (tag: googleapis-6ef6c29b013bfb4fc2aed6add836be637d754e8d, tag: googleapis-08ae6839a6a66955c57de608972ecbd101986cbd) feat(googleads): protos for v8.1 of Google Ads API
```

However, notice that the older commit has the tag `googleapis-08ae6839a`.     That's because commit 08ae6839a in googleapis triggered no changes to the code in googleapis-gen.

**Comment by bcoe** [comment]
@SurferJeffAtGoogle thanks for checking 👍 I did see two changes come in today. I was mainly concerned because we'd just switched branches, and I hadn't seen a change since.
