### ISSUE TITLE
autoapprove: 503, Server Error: Sorry, this diff is taking too long to generate

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#2479]
Error in logs `503, Server Error: Sorry, this diff is taking too long to generate`, resulting from large upstream repo that has auto-approve installed:

https://github.com/Rplayoriginal/docs

**Comment by bcoe** [comment]
This same problem is happening to `generated-files-bot`, due to the same upstream repository.

**Comment by bcoe** [comment]
And to `blunderbuss`.

**Comment by sofisl** [comment]
@bcoe, I couldn't find that error in the logs in auto-approve recently. If it's still happening, it's probably [here](https://github.com/googleapis/repo-automation-bots/blob/cd14097aae09e351519ebf739ab1db99883c6f16/packages/auto-approve/src/get-pr-info.ts#L43). I could catch that error, but my concern is that eventually we do something with that patch, so if it's not generated then I'm concerned that we won't be able to execute the rest of the logic. So, perhaps for auto-approve, it makes sense to have it error? I'm not sure though because I can't inspect the logs for it.

**Comment by bcoe** [comment]
@sofisl if we haven't seen this issue recently, let's close it 👍
