### ISSUE TITLE
[release-trigger][java] Release was triggered twice for java-bigtable-hbase

### ISSUE THREAD

**Issue by kolea2** [googleapis/repo-automation-bots#3016]
See: https://github.com/googleapis/java-bigtable-hbase/pull/3303

Release was successful on the first run, not sure why it was retriggered but failed since it was already released.

**Comment by bcoe** [comment]
I've been seeing this happen around 50% of the time with Node.js repositories, here's another example:

https://github.com/googleapis/nodejs-document-ai/pull/299

If we think the problem is eventual consistency, what if after creating a release we delayed a response until we saw the appropriate information on GitHub, before exiting?

Another cause, that I can think of, could there be two events triggered in parallel when we merge, with one opening a new release PR, and the other creating the release?

**Comment by chingor13** [comment]
@bcoe This original issue is for the release-trigger bot, not release-please.

**Comment by chingor13** [comment]
See https://github.com/googleapis/release-please/issues/1208 for duplicate PR issue
