### ISSUE TITLE
[release-trigger] publication jobs failing to run

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#3223]
I have noticed several times in the past week where a publication job never triggers post release:

https://github.com/googleapis/nodejs-googleapis-common/issues/448
https://github.com/googleapis/google-api-nodejs-client/issues/2901

It's been happening enough this week as to be notable.

## Note

Manually running the publication jobs has been working, so it seems to be the event being lost that triggers kokoro.

**Comment by chingor13** [comment]
The bot has no way of knowing whether the job actually starts or succeeds. It's using the DRIFT job trigger via pubsub.

On the first one, it did enqueue the request because it added the triggered label. On the second it did trigger, but the request actual publish job failed. There's nothing we can do in the bot to detect if the job never starts from the pubsub queue (except via polling which is exactly what failurechecker bot is doing).

**Comment by chingor13** [comment]
The upcoming release-conductor project should be able to replace the release-trigger bot and track status of the release job.
