### ISSUE TITLE
Buildcop removes some labels when opening/closing an issue

### ISSUE THREAD

**Issue by kurtisvg** [googleapis/repo-automation-bots#339]
When blunderbuss opens/closes an issue, it sometimes drops labels:

![image](https://user-images.githubusercontent.com/31518063/75367375-0f570300-5875-11ea-8336-5b5086a96e1b.png)

**Comment by tbpg** [comment]
The issue is the issue update API call completely replaces the current labels:
https://github.com/googleapis/repo-automation-bots/blob/3c7a3bfe7b4cf24f2a18822e9cf38fb49cd24f6e/packages/buildcop/src/buildcop.ts#L255-L261

We should merge the desired labels with the existing labels before calling update.
