### ISSUE TITLE
Redesign merge-on-green to use native branch protection vs. sloth

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#343]
Starting an issue to have a discussion around this approach.

Currently, we use sloth/repos.json and sloth/required-checks.json to enforce required checks in our repositories, instead of checking to see if the branch has its own protection. The reason we did it this way is because we weren't sure all repos had set up their required checks appropriately. 

However, this setup is causing a couple of issues, namely, around increasing the scope of merge-on-green. On the one hand, we need to make custom changes for each repo that wants to use the bot based on their rules for requiring enforced checks by changing the files above. Furthermore, it limits our scope and forces the question of how we add support for repos that are outside of the purview of sloth/repos.json, and furthermore, outside of Google.

I guess the real question at hand would be: do we want to put the burden on the user or on the bot to decide which tests are required?

Would love to get input here from @bcoe and @JustinBeckwith. Also, adding in @gogasa for visibility, as his repos prompted the discussion!

**Comment by lesv** [comment]
When a repo has set things up we should trust it's judgement.

**Comment by JustinBeckwith** [comment]
I look at these as two separate problems.  For MoG - I think it's irresponsible of us to put something like this out there, if it doesn't validate the repo in question has master branch protection enabled.  It would be far too easy for someone to pick this up, and expect it to wait for all checks to turn green.  As far as I understand though - that's not what it does.  I *think* it only waits for _required_ status checks to complete, right?

The risk is that someone starts using it, and merging PRs before CI ever finishes because none of the checks are required. 

I feel strongly about decoupling this logic from sloth.  Sloth is a tool that today is making it easier for us to configure policy on a repo, and keep it up to date.  That's a great way to make sure master branch protection is enabled, but not a promise that it will stay that way :) Let's decouple these tools in our heads.

@lesv I'm not sure exactly what you're advocating for :) Can you be a little more explicit?

**Comment by sofisl** [comment]
@JustinBeckwith, I'm very partial to your approach, especially with an eye to expanding its use. A further question might be, should we have sloth as an 'ultimate backup', specifically for our repos (if there are no required checks on Yoshi libraries)? Or just have them all die by the same sword?

Also, in speaking with @bcoe about this, we might also start thinking about building a bot to automate running sloth so as to eliminate the concern entirely if our repos have the appropriate required checks in place. What do you think about stacking the work in that way, i.e., build 'slothbot' first, then update MoG?

**Comment by gogasca** [comment]
Just for reference:
This is our repo: [ai-platform-samples](https://github.com/GoogleCloudPlatform/ai-platform-samples), here are the required actions:

- Kokoro CI - Python 3.5
- Kokoro CI - Python 3.7
- cla/google

**Comment by sofisl** [comment]
Addressed by PR #369
