### ISSUE TITLE
Owl Bot Post Processor for .NET times out after 40 minutes.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/repo-automation-bots#4087]
In https://github.com/googleapis/google-cloud-dotnet/pull/8927, the post processor timed out after 40 minutes.  It was making continuous progress.  The change to the proto generator version means the code for all the APIs changed so the post processor had a lot of work to do.  The simplest solution would be to increase the timeout.

What does @jskeet think?

**Comment by jskeet** [comment]
This basically only happens when there's a generator change - which we normally prepare for by rerunning the generator manually on everything anyway. (So I'd hope that the result would be a no-op; there are actually some ordering issues which I need to clean up, but that's a different matter.)

Basically, if we think the timeout can be increased without causing problems, that's great - but equally it's not really hurting us much, so if there are downsides to increasing the timeouts, I'm happy to stay as we are.

**Comment by jskeet** [comment]
Just as a heads-up, you're likely to see another of these shortly :)
