### ISSUE TITLE
bug(snippet-bot): Some samples that are being used are reported as unused.

### ISSUE THREAD

**Issue by amanda-tarafa** [googleapis/repo-automation-bots#4588]
- I've created https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1873 to delete IoT samples.
- Snippet-bot is reporting that no samples are used.
- But https://cloud.google.com/iot/docs/samples/iot-patch-rsa#iot_patch_rsa-csharp is pointing to https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/HEAD/iot/api/CloudIotSample/Program.cs

**Comment by tmatsuo** [comment]
That URL `https://cloud.google.com/iot/docs/samples/iot-patch-rsa#iot_patch_rsa-csharp` is created by the sample browser. Snippet-bot ignores those URLs because the sample browser will self heal (in this case, it will delete the page automatically).

So, feel free to merge the original PR.

Closing this issue
