### ISSUE TITLE
[Owl Bot bootstrapper] Can you provide a way to test language-specific container?

### ISSUE THREAD

**Issue by suztomo** [googleapis/repo-automation-bots#4661]
What I want to do:

Build a language specific container in my local Docker:

```
suztomo@suztomo:~/google-cloud-java/generation/new_client$ docker build .
Sending build context to Docker daemon   42.5kB
Step 1/6 : FROM ubuntu:22.10
 ---> 0f175c10c2b4
Step 2/6 : WORKDIR /workspace
 ---> Using cache
 ---> d887d6ad5563
Step 3/6 : ADD owlbot-bootstrapper-java.sh /workspace
 ---> Using cache
 ---> b44725624cb0
Step 4/6 : ADD new-client.py /workspace
 ---> Using cache
 ---> 3aeb777accb0
Step 5/6 : ADD templates /workspace
 ---> Using cache
 ---> 48325dd510b0
Step 6/6 : ENTRYPOINT ["/workspace/owlbot-bootstrapper-java.sh"]
 ---> Using cache
 ---> 1ee4f0eed30c
Successfully built 1ee4f0eed30c
```

and use the container for bootstrap command:

```
suztomo@suztomo:~/google-cloud-java/generation/new_client$ C=1ee4f0eed30c; bootstrapper run-trigger pre-process   --apiId=apikeys   --language=java   --languageContainer=$C   --repoToClone=git@github.com:googleapis/google-cloud-java.git --skipIssueOnFailure
```

However, because 1ee4f0eed30c is not available in Cloud Build environment, I cannot test the container.

**Comment by sofisl** [comment]
I think I could work on this in H1. However, in the meantime, I think you could test by pushing this to a personal project, like so:

```
docker build . --tag gcr.io/personal-project/container-name
docker push gcr.io/personal-project/container-name
```

Once your container is working in isolation, this step should not take too much development.

**Comment by sofisl** [comment]
@suztomo, given that the process uses [Cloud Build](https://github.com/googleapis/repo-automation-bots/blob/67dffcaabbc8b277009ea73b1dce9d32d6a98951/packages/owlbot-bootstrapper/cli/cloudbuild-owlbot-bootstrapper.yaml#L55) to call the containers, I don't see a way of testing the process with a local container, since Cloud Build wouldn't have access to the container built locally. I think you'd need to push it in order to run it with the CLI.

In order to test locally, I recommend two alternatives:

1) Running your language-specific container on a clone of your mono repo. The first step of the common container merely clones your mono repo, and then runs your language container in that workspace (with the environment variables set from the CLI). To test, just set the environment variables  listed [here](https://github.com/googleapis/repo-automation-bots/blob/67dffcaabbc8b277009ea73b1dce9d32d6a98951/packages/owlbot-bootstrapper/cli/cloudbuild-owlbot-bootstrapper.yaml#L56), and call `docker run your-container` in a clone of your repo.

2) Alternatively, or additionally, you can just deploy your iterations to a personal project, like so:

```
docker build . --tag gcr.io/personal-project/container-name
docker push gcr.io/personal-project/container-name
```

Feel free to reopen if you have any other thoughts.
