### ISSUE TITLE
bug(release-please): duplicate commit messages in the release notes for PHP

### ISSUE THREAD

**Issue by bshaffer** [googleapis/repo-automation-bots#4989]
Hello!
I've found our commit messages are receiving duplicate entries:
<img width="812" alt="Screenshot 2023-03-01 at 5 52 51 AM" src="https://user-images.githubusercontent.com/103941/222159651-48ebd297-a4a6-4224-b664-1c8e1738d525.png">

I think this has to do with the commit message being read and the commit messages extracted. This is great, and I love it! How can we ensure the messages aren't duplicated? Here are some ideas:

1. Strip the component name (e.g. `[BigQueryDataTransfer]` above) and dedupe the result with the other commit messages
2. If semantic commit(s) are found in the body of the PR, do not include the PR title in the release notes
3. If it's an `owl-bot` PR AND <span>#</span>2 is true, don't include the PR title in the release notes

This could be a two-birds-with-one-stone type of thing, since I would really like to strip the `[ComponentName]` from the release notes, if possible. If it's too much trouble, we can also just remove the `[ComponentName]` manually from the merge commit.

Thanks!

**Comment by chingor13** [comment]
This is duplicated because these commit (https://github.com/googleapis/google-cloud-php/commit/513701d0e9f2088a37ca952490a46407c1f131dc) has multiple conventional commit messages that are nearly the same. In general, release-please should not be changing the commit messages that are being put in by the maintainers. Instead, make sure the commit messages are curated to follow the conventional commits spec.

**Comment by bshaffer** [comment]
That makes sense. Maybe i can open up a feature request to provide custom templates for the OwlBot commit messages / descriptions then?
