### ISSUE TITLE
[repo-metadata-lint] does not support non-gRPC APIs

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#5036]
The linter is using the [API index](https://github.com/googleapis/googleapis/blob/master/api-index-v1.json) to gather the list of valid api_ids (from scanning the googleapis/googleapis service configs).

https://github.com/googleapis/googleapis/commit/208d6b53fecb1278b74fc04bee98acc82369d915 removed the unavailable bigquery v2 gRPC endpoint which removed it from the API index.

**Comment by chingor13** [comment]
Option: maintain a hard-coded list in the bot.
Option: try and gather the api id from the full product list from the DRIFT product database export (the snippet-bot is combining this export with the data from service config files)

**Comment by chingor13** [comment]
Actually, looks like the api id is not available in DRIFT's data, so we may just have to go with a curated extra allowlist

**Comment by chingor13** [comment]
> Actually, looks like the api id is not available in DRIFT's data, so we may just have to go with a curated extra allowlist

Looks like we actually only care about the api_shortname which is available in the DRIFT data.

**Comment by amanda-tarafa** [comment]
Just FYI: The api short name in DRIFT doesn't always match the host name of the API default URL. If the repo metadata is generated using the host name of the API default URL (most likely as I don't think any generator depends on DRIFT), then there will be mismatches. That's why we have the SnippetBot label for ignoring mismatches between what the generator uses and what's in DRIFT.
