### ISSUE TITLE
[merge-on-green] Python dependency PRs sometime don't auto-approve all commits

### ISSUE THREAD

**Issue by bourgeoisor** [googleapis/repo-automation-bots#5099]
I noticed that PRs for Python dependencies don't have all of their commits auto-approve, which leaves PRs stuck in a not-approved state and prevents auto-merging.

Noticed this first here: https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1575

1) Jun 7, 4:40pm - new changes, approve!
2) Jun 7, 7:23pm - new changes
3) Jun 8, 6:11pm - new changes, approve!
4) Jun 12, 1:27pm - new changes
5) Jun 13, 1:49pm - new changes

Another e.g. https://github.com/GoogleCloudPlatform/bank-of-anthos/pull/1580 (can provide more examples if needed)

**Comment by sofisl** [comment]
Hi @bourgeoisor, this is a factor of using the "automerge: exact" label. The exact label will remove an approving review when a new commit is added. So, it's technically doing the right thing (this is for added security, that way a malicious actor can't push a commit to the PR and auto-approve just merges it).

This issue is a bit complicated to resolve, see for example: https://github.com/googleapis/repo-automation-bots/issues/5096.

Technically, I think this is more of a feature request for merge-on-green, instead of a bug, since it is doing the correct thing (it is removing approvals once something is changed). I'll have to give this a deeper look to see how to best fix this in automerge.

**Comment by sofisl** [comment]
Upon further investigation, this does seem to be a bug in the logic. Currently, auto-approve will skip doing anything to a PR if it sees it already approved. However, the situation that seems to be occurring is that the PR is already approved, but merge-on-green removed the automerge:exact tag (probably because the time has run out, maybe because a test hasn't finished running, etc). Instead of skipping, we need to still attempt to add the label if there is an approval.
