### ISSUE TITLE
Query request(auto-approve): Request for available/possible customisation to use auto-approve bot

### ISSUE THREAD

**Issue by msampathkumar** [googleapis/repo-automation-bots#5241]
This is a query request for [auto-approve](https://github.com/googleapis/repo-automation-bots/tree/main/packages/auto-approve).

To use auto-approval bot on repositories like https://github.com/GoogleCloudPlatform/python-docs-samples for package update PR [- example](https://screenshot.googleplex.com/Ao4WaT3y5P2KiBj), we may need following customisation for effective(risk) management. Kindly help me with following questions.  (Yes/No/Need a FeatureRequest or online response is enough.)

Can auto-approve bot configuration file allow to do the following?

1. Enable or disable the bot
2. Check and approve only at a specified time (Ex: At GMT 23:00 hrs)
3. Check who is PR author(dependa-bot, renovate-bot)
4. Check which files are updated the PR(file type, file Name)
5. (Optional) Any scope to list all files for which the bot can give approval
6. Inclusive or Exclusive list of files, for which a bot may/may not approve the PRs
7. Any scope to auto-approve and merge the PR?
   Update: I believe `merge-on-green` bot will be better option.
8. (Optional) Check no.of lines update in the PR?
    Many of our PRs are one liner updates, so it would be re-assuring to have a no.of update lines as filter option.
9. (Query) If the PR requires two approval, is it possible auto-approve & merge PR?
10. Check & approve only if the CICD test pass

If you have any example config-template kindly share it.

**Comment by chingor13** [comment]
The configuration for the auto-approve bot is pretty basic - it intentionally is not a rules engine with lots of customization because it would be easy to misconfigure and allow attackers to sneak unwanted code in.

1 - the bot will not do anything without a `.github/auto-approve.yml` file.
2 - Time options are not available. It is event based on PR creation/update.
3-6, 8 - These are built into the aggregate rules in code. If you have a specific use case, you can submit a PR that introduces a new specific ruleset.
7,9,10 - The auto-approve bot does not actually do any merging. It adds an `automerge` label to the PR and the merge-on-green bot does the merging. merge-on-green checks required approvers and that CI passed based on branch protection rules.

**Comment by sofisl** [comment]
Thanks @chingor13!

@msampathkumar, here are some examples of other customized rules:

https://github.com/googleapis/repo-automation-bots/issues/5006
https://github.com/googleapis/repo-automation-bots/issues/4993
https://github.com/googleapis/repo-automation-bots/issues/5062
