### ISSUE TITLE
auto-approve bot: The bot isn't approving PR as intended.

### ISSUE THREAD

**Issue by msampathkumar** [googleapis/repo-automation-bots#5272]
Thanks for stopping by to let us know something could be better!

Renovate bot PRs
* https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11092
* https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11090
* https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11089

Dependa bot PRs

* https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11071 
* https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11049
* https://github.com/GoogleCloudPlatform/python-docs-samples/pull/11048

For all the above PR the CICD logs for Auto Approve Bot are as follows

![image](https://github.com/googleapis/repo-automation-bots/assets/6114993/00b2f93c-7bfb-4717-90b0-0980ff7a2372)

__Request:__

1. Kindly add few user logs to understand the Auto-Approve Bot's approval criteria. For example `Log: XYZ package Version update is a major change. Log: Auto-Approve skipping approve process`, `Log: ABC package Version update is a minor change. Log: Auto-Approve approved the PR`

2. Update the Auto-Approve bot to approve minor package changes.

**Comment by sofisl** [comment]
Hi @msampathkumar, the check you're pointing out is actually a check for the auto-approve.yaml file, [this one](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/auto-approve.yml). This is more of a legacy check, back when the configuration file was more customizable (so that this file couldn't be hijacked to approve random PRs).

I do agree though, that it would be nice to have comments if a PR fails. However, it's a tricky line, because we also don't want it to be noisy (we don't want all PRs to get comments on why they were not auto-approved, some aren't real candidates). I'll have to think about this more; I'll create a separate feature request.

In the meantime, let's focus on what isn't being approved. It seems to me like just dependabot ones are being ignored; I investigated and opened a [PR](https://github.com/googleapis/repo-automation-bots/pull/5274). Do the renovate-bot ones look right to you?

**Comment by msampathkumar** [comment]
@sofisl yup `dependabot[bot]`
