### ISSUE TITLE
merge-on-green: change the default behavior to not merge if new changes are pushed

### ISSUE THREAD

**Issue by kurtisvg** [googleapis/repo-automation-bots#579]
Currently MoG allows the author of the PR to make additional changes, including merge, rebase, or just add new commits. While this is desired for certain use cases, it's also a potential security flaw. An author without write access can push additional changes to a PR after already receiving a review, which may be non obvious to the reviewer applying the label. 

I suggest that we make the default automerge behavior safe by default and disallow changes, and add a different label (perhaps `merge-on-green: allow changes`) that instructs MoG to allow different changes such as rebase, merge, or new changes. 

It might also be nice to have specific labels that limit what the user can do (like "only-rebase" or "only-merge") to allow for those use cases, but I'm not sure how feasible those are.

**Comment by sofisl** [comment]
@JustinBeckwith @stephaniewang526 - I think this issue speaks directly to this bug: b/158236015

I think we need to have a larger discussion about this request. I'm not opposed to having different functionalities as @kurtisvg recommended, but I don't really see how that would stop a malicious actor from just applying a less-safe label to a given PR. But, since internal anyways, maybe we don't really have to worry about this case.

Curious to hear what you all think!

**Comment by kurtisvg** [comment]
> I don't really see how that would stop a malicious actor from just applying a less-safe label to a given PR. But, since internal anyways, maybe we don't really have to worry about this case.

To clarify, I'm not worried about the person applying the label being malicious, but instead the author of the PR that the label is applied too. 

Image this scenario: 
- A third-party opens a PR for a small fix
- it's quickly approved and someone applies the automerge label to it
- the author then pushes a series of new commits to do something malicious
- MoG merges the commits

This behavior is clearly useful for _some_ cases (such as renovate or other bots that may continually update/rebase), but probably shouldn't be the default behavior (since it may not be clear to the party that applies the label this could happen).
