### ISSUE TITLE
flakybot: Allow priority of label to be configured

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#591]
I am looking at enabling our flaky test detection bot more widely for Node.js and, in case this ends up turning into a mountain of work, I would love to be able to configure issues as P1s vs., P2s.

**Comment by tmatsuo** [comment]
Probably we should follow the pattern for config file?

The tricky part is that because flakybot is mostly implemented as a pubsub handler, we'll probably need to implement the code for fetching the config file. It's not very complicated, but needs to be extra cautious not to break the app.

If we start to have config file, it is a good idea to implement config schema check on PRs. I'll start from there.

**Comment by tbpg** [comment]
We could also skip the config file and add a flag to the `flakybot` command line tool.
