### ISSUE TITLE
Disable esModuleInterop

### ISSUE THREAD

**Issue by chingor13** [googleapis/repo-automation-bots#62]
Ideally, we should not need `esModuleInterop` configuration for tsconfig.

**Comment by JustinBeckwith** [comment]
I'm going to go the other way on this one :) The default config for TypeScript these days is to enable esModuleInterop.  We disable it by default in other modules because it can have downstream effects for consumers of a library compiled with the flag enabled.  In this case - the bots are the end user app, so there are no real negative side effects.  I'm closing this out - but please do let me know if I'm missing something!
