### ISSUE TITLE
sync-repo-settings: debug the edge cases that are responding with exceptions in sync-repo-settings

### ISSUE THREAD

**Issue by bcoe** [googleapis/repo-automation-bots#732]
To unblock failures we're seeing in our task queues, I've added back some error handling to `sync-repo-settings`:

https://github.com/googleapis/repo-automation-bots/pull/722

I haven't enumerated a list of which repos throw these specific errors, someone should take on the work to do this and see if we can remove additional catches.

@sofisl points out that GitHub's error codes might not be granular enough to truly identify certain types of errors, we should also consider whether we could look at more specific components of the payload to decide the type of error.

CC: @sofisl, @JustinBeckwith

**Comment by JustinBeckwith** [comment]
We did the digging here, and @sofisl is right - the problem is that with the addition of local file based permissions, the bot now needs access to read source repository code.  Today we don't ask for that permission, and it's causing failures when we don't have access.  A few thoughts here:
1. We need to update the requested scopes for the bot in production (this can't be done via code today)
2. We did apply a `try`/`catch` around the offending code, and that appears to have captured the problem.  We are still logging the errors.
3. Because users of the bot would have to re-grant rights, there is never a promise these errors won't happen.  So ... I'm unsure if they should be seen as errors or warnings.  In the wild, these are not actionable.  But for specifically our repositories, they are.  

@bcoe curious what you think here.

**Comment by bcoe** [comment]
@JustinBeckwith I think for actionable errors, where it would be nice to get to eventually would be that we open an issue describing why the bot couldn't run on a given repository; this would help users better debug.

Just a thought of where it might be nice to get to?

**Comment by JustinBeckwith** [comment]
Comically to do that, folks would need to grant issue create rights to the bot 😆 But agreed, that would be a really nice thing to detect and file issues for.

**Comment by SurferJeffAtGoogle** [comment]
Closing because this bug has been inactive for over one year.
