### ISSUE TITLE
[build cop bot] Missing reports

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/repo-automation-bots#818]
On python-docs-samples, we had missing reports.

[Build](https://source.cloud.google.com/results/invocations/df87f819-2b8c-457e-b8bc-7447617e0471/targets)

Log:
```
ERROR streaming_beam_test.py::test_dataflow_flex_templates_pubsub_to_bigquery
========================= 1 passed, 1 error in 37.24s ==========================
Command pytest --junitxml=sponge_log.xml failed with exit code 1
Session py-3.6 failed.
[Buildcop] Sending logs to Build Cop Bot...
[Buildcop] See https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop.
[Buildcop] Published sponge_log.xml (1409596648235567)!
```

The same test failed in [another build](https://source.cloud.google.com/results/invocations/7cc7af55-23b3-44bb-a99d-e2c103c31f42/targets)

Log:
```
=========================== short test summary info ============================
ERROR streaming_beam_test.py::test_dataflow_flex_templates_pubsub_to_bigquery
========================= 1 passed, 1 error in 37.05s ==========================
Command pytest --junitxml=sponge_log.xml failed with exit code 1
Session py-3.7 failed.
[Buildcop] Sending logs to Build Cop Bot...
[Buildcop] See https://github.com/googleapis/repo-automation-bots/tree/master/packages/buildcop.
[Buildcop] Published sponge_log.xml (1409658205614237)!
```

**Comment by tbpg** [comment]
Closing following offline discussion. There are recent issues that have been filed since this. So, we think we're OK now.

I checked the logs and saw successful invocations over the last week for this particular test. I didn't see a failure for it. I don't know why.

We thought it was maybe a Cloud Tasks payload size issue, but the bot is no longer using Cloud Tasks. But, the bot stopped using Cloud Tasks before this issue (we think).
