### ISSUE TITLE
feat(snippet-bot): query tag database for TAG already existing

### ISSUE THREAD

**Issue by lesv** [googleapis/repo-automation-bots#891]
Sometimes a developer copy and pastes from an existing sample and accidently leaves a tag in the copied code.  It would be nice if:
* Duplicate tags were called out (showing all files involved)
* That a broken tag was correct in another file -- action likely remove tag
* That a tag was unique - likely a missing tag or misspelled one

**Comment by tmatsuo** [comment]
This is probably harder than it first appears. These 3 checks all assume that the region tags are unique. I think that assumption is probably wrong.

We sometimes move sample code around for reasons. When we do this, we of course need to allow duplicate region tags for a time being.

The difficult thing for the bot is to determine which duplicate is intentional and which duplicate is not.

**Comment by lesv** [comment]
I was thinking that you'd just call them out, but not annoy them.  List all references and if they close the issue - ignore it (possibly for some set amount of time)

**Comment by tmatsuo** [comment]
Adding a FYI comment sounds reasonable.

**Comment by SurferJeffAtGoogle** [comment]
Closing because this bug has been inactive for over one year.
