### ISSUE TITLE
feature request(mog): Help MOG not hit rate limits

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#918]
MOG hits a lot of rate limits. Might be good to try to use something like etags:
https://developer.github.com/v3/

**Comment by JustinBeckwith** [comment]
I took a somewhat closer look here.  Good news - there are some really low hanging watermelons 🍉   I saw we were getting pinged for abuse on the endpoint that gets PR info.  We also subscribe to PR events though!  One easy win would be using the `app.on('pull_request')`  we already have, and let that populate a table in the Datastore on every event.  We would also need to look for cases where PRs are closed, and delete them from the table.  Then, in the places where you would otherwise query for shallow data on the PR (I saw many), you can just use the Datastore table instead of reaching out to the API.  Happy to pair for an hour or two to try this approach out!

**Comment by sofisl** [comment]
@JustinBeckwith, thanks for digging into this! The main reason we re-request the PR info is to make sure the PR has _not_ been closed since someone tagged the PR, or to check on statuses, etc.

If I'm understanding you correctly, maybe we could listen to PR events, and update our main Datastore table whenever these things change. I think that could work!

**Comment by chingor13** [comment]
I think the problem here is that if we do hit rate limits, we aren't detecting it and we're removing the PR. Removing the PR does 2 things: remove it from the database and then remove the label from the PR. We're not removing the label so we have no signal that merge-on-green has stopped watching the pull request.

**Comment by chingor13** [comment]
I'm going to change this to a bug - this is causing us a lot of pain to the point where I can trust bulk tagging automerge because I have to babysit the remaining PRs that still have the automerge label that won't be checked.

**Comment by sofisl** [comment]
@chingor13, I want to let you know that I have this on my radar. I want to upgrade the bots before we continue making changes, since MOG is still using v16 of the octokit library. If I have to add any new methods, I'd rather not have to undo them after the upgrade.
