### ISSUE TITLE
auto-label: distinguish between 'docs' as a type of issue and an API

### ISSUE THREAD

**Issue by sofisl** [googleapis/repo-automation-bots#955]
![Screen Shot 2020-09-14 at 10 36 52 AM](https://user-images.githubusercontent.com/55454395/93120264-f2024e80-f677-11ea-991f-2e5bacb3c2dc.png)

Auto-label thinks this is related to the docs API, but it's actually for the Drive docs. This is a pretty minor inconvenience to fix, but just a heads up.

**Comment by tbpg** [comment]
(`type: bug` needs a `priority` to be "triaged.")

I'm not sure how to handle this one. If the bug was filed as "docs(drive): pagination ..." it would be detected as `api: drive`. But, this is an unfortunate case of conventional commit type overlapping with an API name. We could special case `docs`, but there could legitimately be `api: docs` issues.

So, I'm inclined to close this as won't fix. What do you think?

**Comment by sofisl** [comment]
Ah, I think that's a helpful explanation. Yeah, I'm fine with that, given that docs is an API name and a type. Plus, it's not too much of a hassle to change! At least we've documented it as a known issue.

**Comment by tbpg** [comment]
I've seen this several more times. I think we should disable automatic labeling of `api: docs`.
